name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install system deps
        run: sudo apt-get update && sudo apt-get install -y ffmpeg
      - name: Install Python deps (CI)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-ci.txt
          pip install -r requirements-dev.txt
      - name: Lint & type-check
        run: |
          ruff --version
          black --check .
          ruff check .
          mypy apps || true
      - name: Run tests
        run: pytest -q
